#!/usr/bin/env bash

PROCESSES_NUM=$1
OPENFACE_PATH=$2
UPLOADS_PATH=$3
USER_DATA=$UPLOADS_PATH/users
ALIGNED_DATA=$UPLOADS_PATH/users_aligned
FEATURE_DIR=$UPLOADS_PATH/feature

for N in {1..$PROCESSES_NUM};
do $OPENFACE_PATH/util/align-dlib.py $USER_DATA align outerEyesAndNose $ALIGNED_DATA --size 96 &
done

$OPENFACE_PATH/batch-represent/main.lua -outDir $FEATURE_DIR -data $ALIGNED_DATA

$OPENFACE_PATH/demos/classifier.py train $FEATURE_DIR
